In [ ]:
import numpy as np

# Random 4x4 matrix
matrix = np.random.rand(4, 4)

print("Original Matrix:\n", matrix)

Original Matrix:
 [[0.48436866 0.41841968 0.32553889 0.653545  ]
 [0.76992958 0.11671264 0.88446617 0.18803465]
 [0.10674165 0.88022166 0.50484133 0.7016461 ]
 [0.68429226 0.11441269 0.80177283 0.92864889]]


In [2]:
# Replace the first column with all ones
matrix[:, 0] = 1

print("Modified Matrix:\n", matrix)

Modified Matrix:
 [[1.         0.41841968 0.32553889 0.653545  ]
 [1.         0.11671264 0.88446617 0.18803465]
 [1.         0.88022166 0.50484133 0.7016461 ]
 [1.         0.11441269 0.80177283 0.92864889]]
