In [ ]:
import numpy as np

# Random 3x3 matrices
matrix1 = np.random.randint(1, 10, size=(3, 3))
matrix2 = np.random.randint(1, 10, size=(3, 3))

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")  
print(matrix2)

Matrix 1:
[[3 2 5]
 [5 8 5]
 [4 3 6]]
Matrix 2:
[[5 8 8]
 [2 7 1]
 [3 4 8]]


In [ ]:
addition = matrix1 + matrix2
subtraction = matrix1 - matrix2
multiplication = matrix1 * matrix2
division = matrix1 / matrix2  

print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)


Element-wise Addition:
 [[ 8 10 13]
 [ 7 15  6]
 [ 7  7 14]]

Element-wise Subtraction:
 [[-2 -6 -3]
 [ 3  1  4]
 [ 1 -1 -2]]

Element-wise Multiplication:
 [[15 16 40]
 [10 56  5]
 [12 12 48]]

Element-wise Division:
 [[0.6        0.25       0.625     ]
 [2.5        1.14285714 5.        ]
 [1.33333333 0.75       0.75      ]]


In [ ]:
# Calculate the determinant 
det_matrix1 = np.linalg.det(matrix1)
det_matrix2 = np.linalg.det(matrix2)

print(f"\nDeterminant of Matrix 1: {det_matrix1}")
print(f"Determinant of Matrix 2: {det_matrix2}")


Determinant of Matrix 1: -5.99999999999999
Determinant of Matrix 2: 51.999999999999964
