In [ ]:
import numpy as np

# Create random matrix and array
matrix = np.random.randint(1, 10, size=(3, 3))
array = np.random.randint(1, 10, size=3)

print("Matrix:")
print(matrix)
print("1D Array:")
print(array)

Matrix:
[[8 7 4]
 [9 4 9]
 [5 9 7]]
1D Array:
[6 4 8]


In [ ]:
# Use broadcasting 
result = matrix + array
print("\nResult of Broadcasting (Matrix + Array):\n", result)


Result of Broadcasting (Matrix + Array):
 [[14 11 12]
 [15  8 17]
 [11 13 15]]
